# Check with travis lint .travis.yml.
# TODO: we want this to be xenial, but travis doesn't support it yet.
# dist: xenial
language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get install graphviz"
  - "sudo pip install -r requirements.txt"
install:
  - "make"
  - "cwd=$(pwd) ; tarball=`echo $cwd/dist/ryu-faucet*tar.gz` ; sudo pip install file:$tarball"
  - "[ -f /etc/ryu/faucet/faucet.yaml-dist ]"
# We want to run actual mininet based tests too. Prefer xenial
# but perhaps can run container-inside-container inside this container..
script:
  - "pylint -E src/ryu_faucet/org/onfsdn/faucet/*.py"
  - "cd ./tests ; ./test_config.py ; ./test_check_config.py ; ./test_valve.py"
