language: python
python:
  - "2.7"
before_install:
  - "sudo apt-get install graphviz"
  - "sudo pip install -r requirements.txt"
install:
  - "make"
script:
  - "cd ./tests ; ./test_config.py ; ./test_check_config.py ; ./test_valve.py"
