FROM reannz/faucet-tests

RUN \
  apt-get update && \
  apt-get install -qy --no-install-recommends \
    libcurl4-gnutls-dev \
    libssl-dev \
    openssl \
    build-essential \
    dhcpcd5 \
    udhcpd

RUN \
  git clone https://github.com/Bairdo/hostapd-d1xf.git && \
  cd hostapd-d1xf/hostapd && \
  git checkout username-fix-2 && \
  printf "interface=portal-eth0\n\
driver=wired\n\
logger_stdout=-1\n\
logger_stdout_level=0\n\
ieee8021x=1\n\
eap_reauth_period=3600\n\
use_pae_group_addr=0\n\
eap_server=1\n\
eap_user_file=/root/hostapd-d1xf/hostapd/hostapd.eap_user\n" > wired.conf && \
  printf '"user"          MD5     "password"\n\
"host110user"   MD5     "host110pass"\n\
"host111user"   MD5     "host111pass"\n\
"host112user"   MD5     "host112pass"\n\
"host113user"   MD5     "host113pass"\n\
"host114user"   MD5     "host114pass"\n' > hostapd.eap_user


RUN \
  pip3 install requests

CMD ["/faucet-src/docker/run_authtests.sh"]
