version: '2.1'

services:
    faucet:
        restart: always
        image: 'faucet/faucet-pi'

        volumes:
            - '/var/log/faucet:/var/log/faucet'
            - '/etc/faucet:/etc/faucet'

        ports:
            - '6653:6653'
            - '9302'
        environment:
            FAUCET_CONFIG_STAT_RELOAD: '${FAUCET_CONFIG_STAT_RELOAD}'
            FAUCET_EVENT_SOCK: '${FAUCET_EVENT_SOCK}'
        networks:
            control-plane-net:
                ipv4_address: 172.222.0.103

    gasket:
        build:
            context: '.'
            dockerfile: './Dockerfile.pi'
        volumes:
            - '/var/log/faucet:/var/log/faucet'
            - '/etc/faucet:/etc/faucet'
            - '/var/run/:/var/run/'
        networks:
            default:
            control-plane-net:
                ipv4_address: 172.222.0.100
        ports:
            - 8890:8890/udp
            - 8891:8891/udp

    rabbitmq_adapter:
        restart: always
        depends_on:
            - faucet
        image: 'faucet/faucet-event-adapter-rabbitmq-pi'
        volumes_from:
            - faucet
        environment:
            FAUCET_EVENT_SOCK: '${FAUCET_EVENT_SOCK}'
            FA_RABBIT_HOST: '${FA_RABBIT_HOST}'
            FA_RABBIT_PORT: '${FA_RABBIT_PORT}'
            FA_RABBIT_EXCHANGE: '${FA_RABBIT_EXCHANGE}'
            FA_RABBIT_EXCHANGE_TYPE: '${FA_RABBIT_EXCHANGE_TYPE}'
            FA_RABBIT_ROUTING_KEY: '${FA_RABBIT_ROUTING_KEY}'
        networks:
            control-plane-net:
                ipv4_address: 172.222.0.105


    rabbitmq_server:
        restart: always
        image: 'rabbitmq:3-management'
        networks:
            control-plane-net:
                ipv4_address: 172.222.0.104

        ports:
            - "5672:5672"

networks:
    control-plane-net:
        driver: bridge
        ipam:
            config:
                - subnet: 172.222.0.0/24
