FROM ubuntu:16.04
MAINTAINER Michael Baird <Michael.Baird@ecs.vuw.ac.nz>

RUN apt-get update && apt-get install -y \
    freeradius

EXPOSE \
    1812/udp \
    1813/udp \
    18120

CMD ["freeradius", "-X"]
