FROM faucet/faucet-python3:1.7.0

COPY ./ /gasket-src/

RUN \
  BUILDDEPS='gcc python3-dev musl-dev' && \
  apk -q add -U  $BUILDDEPS && \
  pip3 install --upgrade pip && \
  pip3 install setuptools wheel virtualenv --upgrade && \
  pip3 install -r /gasket-src/requirements.txt && \
  pip3 install /gasket-src && \
  for i in $BUILDDEPS; do apk -q del $i; done

VOLUME ["/etc/faucet/", "/var/log/faucet/", "/etc/hostapd"]

CMD ["/gasket-src/docker/runauth.sh"]
