FROM reannz/faucet-tests

RUN \
  apt-get update && \
  apt-get install -qy --no-install-recommends \
    libcurl4-gnutls-dev \
    libssl-dev \
    openssl \
    build-essential \
    dhcpcd5 \
    python3.5 \
    python3-pip \
    libpython3.5-dev \
    udhcpd \
    isc-dhcp-client

RUN \
  git clone https://github.com/Bairdo/hostapd-d1xf.git && \
  cd hostapd-d1xf/hostapd && \
  git checkout username-fix-2 && \
  sed -ie  's/10\.0\.0\.2/10\.0\.13\.3/g' /root/hostapd-d1xf/src/eap_server/eap_server.c && \
  sed -ie  's/10\.0\.0\.2/10\.0\.13\.3/g' /root/hostapd-d1xf/src/eapol_auth/eapol_auth_sm.c && \
  make && \
  printf "interface=portal-eth0\n\
driver=wired\n\
logger_stdout=-1\n\
logger_stdout_level=0\n\
ieee8021x=1\n\
eap_reauth_period=3600\n\
use_pae_group_addr=0\n\
eap_server=1\n\
eap_user_file=/root/hostapd-d1xf/hostapd/hostapd.eap_user\n" > wired.conf && \
  printf '"user"          MD5     "password"\n\
"host110user"   MD5     "host110pass"\n\
"host111user"   MD5     "host111pass"\n\
"host112user"   MD5     "host112pass"\n\
"host113user"   MD5     "host113pass"\n\
"host114user"   MD5     "host114pass"\n' > hostapd.eap_user


RUN \
  pip3 install --upgrade pip && \
  pip3 install setuptools  virtualenv --upgrade && \
  pip3 install pyyaml requests networkx

RUN mv /sbin/dhclient /usr/sbin/dhclient


RUN \
  mkdir -p /var/log/ryu/faucet && \
  touch /var/log/ryu/faucet/faucet.log 

CMD ["/faucet-src/docker/run_authtests.sh"]
