FROM ubuntu:latest

ENV OVSV="2.7.3"

ENV AG="apt-get -qqy --no-install-recommends"
ENV DEBIAN_FRONTEND=noninteractive
ENV PIPDEPS="setuptools wheel virtualenv"
ENV PIP="pip -q --no-cache-dir install --upgrade"
ENV PIP3="pip3 -q --no-cache-dir install --upgrade"
ENV SETUPQ="setup.py -q"

###
### When apt-get'ing, make sure apt-update always run first per RUN
### to ensure Docker layer cache doesn't use a stale apt database.
###

COPY ./docker/setupproxy.sh /

RUN \
  ./setupproxy.sh && \
  $AG update && \
  $AG install \
    autoconf \
    automake \
    apt-transport-https \
    bc \
    build-essential \
    curl \
    dhcpcd5 \
    fping \
    freeradius \
    gcc \
    git \
    haveged \
    isc-dhcp-server \
    iperf \
    iputils-ping \
    ladvd \
    linux-headers-generic \
    libpython2.7-dev \
    libpython3-dev \
    libssl-dev \
    libtool \
    libyaml-dev \
    lsof \
    netcat \
    ndisc6 \
    net-tools \
    netcat-openbsd \
    openssl \
    openvswitch-common \
    parallel \
    patch \
    psmisc \
    python-pip \
    python3-pip \
    software-properties-common \
    sudo \
    tcpdump \
    tshark \
    udhcpd \
    vlan \
    wget \
    wpasupplicant && \
  git clone https://github.com/openvswitch/ovs -b v${OVSV} && \
  cd ovs && \
  ./boot.sh && ./configure --enable-silent-rules && make -s V=0 install && \
  cd .. && \
  rm -rf ovs && \
  $AG purge $OVSDEPS && \
  $AG autoremove

RUN \
  update-rc.d haveged defaults

###
### TODO: pytype may be slightly stale due to Docker caching.
### Specify versions as we do for mininet if possible.
###

RUN \
  git config --global url.https://github.com/.insteadOf git://github.com/ && \
  /bin/echo -e "https://github.com/mininet/mininet\nhttps://github.com/google/pytype.git" | parallel git clone


### slim down mininet dependencies (to avoid installing X11)
RUN \
  ./setupproxy.sh && \
  $AG update && \
  cd mininet && git checkout 2.2.2 && cd .. && \
  perl -pi -e "s/setup.py/${SETUPQ}/g" mininet/Makefile && \
  perl -pi -e "s/apt-get/${AG}/g" mininet/util/install.sh && \
  for i in ssh pep8 pyflakes python-pexpect pylint xterm ; do perl -pi -e "s/${i}//g" mininet/util/install.sh ; done && \
  mininet/util/install.sh -n && \
  rm -rf mininet


RUN \
  ./setupproxy.sh && \
  $AG update && \
  git clone https://github.com/Bairdo/hostapd-d1xf.git && \
  cd hostapd-d1xf/hostapd && \
  git checkout faucet-tests && \
  make && make install


RUN \
  ./setupproxy.sh && \
  $AG update && \
  $AG purge pylint && \
  $PIP3 pip && \
  easy_install -q -U pip && \
  $PIP pip && \
  $PIP multiprocessing scapy==2.3.2 $PIPDEPS && \
  $PIP3 $PIPDEPS

RUN \
  cd pytype && git submodule init && git submodule update && python2 $SETUPQ install && cd .. && rm -rf pytype

RUN \
  ./setupproxy.sh && \
  git clone https://github.com/faucetsdn/faucet.git /faucet-src&& \
  $PIP3 /faucet-src

###
### To maximize Docker caching, try to keep invariant dependencies above this line.
###

RUN \
  ./setupproxy.sh && \
  $AG update && \
  $AG install -y pkg-config

RUN \
  ./setupproxy.sh && \
  $AG update && \
  $AG install -y libnl-genl-3-dev libnl-3-dev


RUN \
  ./setupproxy.sh && \
  $AG remove -y wpasupplicant && \
  $AG install -y libnl-3-dev && \
  wget https://w1.fi/releases/wpa_supplicant-2.6.tar.gz && \
  tar -xzf wpa_supplicant-2.6.tar.gz && \
  cd wpa_supplicant-2.6/wpa_supplicant && \
  cp defconfig .config && \
  echo 'CONFIG_LIBNL32=y' >> .config && \
  make && cp wpa_cli wpa_supplicant /usr/local/bin


COPY ./tests/config/raddb /etc/freeradius

COPY ./ /gasket-src/

RUN \
  $PIP -r /gasket-src/test-requirements.txt && \
  $PIP3 -r /gasket-src/requirements.txt && \
  $PIP3 -r /gasket-src/test-requirements.txt

CMD ["/gasket-src/docker/runtests.sh"]
