FROM osrg/ryu

RUN \
  apt-get update && \
  apt-get install -qy --no-install-recommends software-properties-common && \
  add-apt-repository -y ppa:longsleep/golang-backports && \
  apt-get update

RUN \
  apt-get install -qy --no-install-recommends \
    bc \
    build-essential \
    dhcpcd5 \
    fping \
    gcc \
    git \
    golang-go \
    influxdb \
    iperf \
    iputils-ping \
    ladvd \
    libcurl4-gnutls-dev \
    libpython2.7-dev \
    libpython3-dev \
    libssl-dev \
    libyaml-dev \
    ndisc6 \
    net-tools \
    netcat-openbsd \
    openssl \
    psmisc \
    python-pip \
    python3-pip \
    sudo \
    tcpdump \
    udhcpd \
    vlan \
    wpasupplicant

RUN \
  git clone https://github.com/Bairdo/hostapd-d1xf.git && \
  cd hostapd-d1xf/hostapd && \
  git checkout Bairdo-patch-1 && \
  printf '"user"          MD5     "password"\n\
"host110user"   MD5     "host110pass"\n\
"host111user"   MD5     "host111pass"\n\
"host112user"   MD5     "host112pass"\n\
"host113user"   MD5     "host113pass"\n\
"host114user"   MD5     "host114pass"\n' > hostapd.eap_user

RUN \
  git clone -b 2.2.2 https://github.com/mininet/mininet && \
  apt-get update && \
  mininet/util/install.sh -nfv && \
  apt-get purge -qy pylint && \
  GOPATH=~/go go get -u github.com/openconfig/gnmi/cmd/gnmi_cli

COPY ./ /faucet-src/

RUN \
  pip install --upgrade pip && \
  pip install setuptools wheel virtualenv --upgrade && \
  pip install -r /faucet-src/test-requirements.txt && \
  pip install exabgp==3.4.20 && \
  pip3 install setuptools wheel virtualenv --upgrade && \
  pip3 install -r /faucet-src/requirements.txt && \
  pip3 install -r /faucet-src/test-requirements.txt && \
  pip3 install /faucet-src

CMD ["/faucet-src/docker/runtests.sh"]
