#!/bin/bash

ipt = "# Generated by iptables-save v1.6.0 on Thu Feb 23 20:20:35 2017
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [2:120]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
-A PREROUTING -d 2.2.2.2/32 -i enp0s8 -p tcp -j REDIRECT
-A PREROUTING -i enp0s8 -p tcp -j REDIRECT
COMMIT
# Completed on Thu Feb 23 20:20:35 2017
# Generated by iptables-save v1.6.0 on Thu Feb 23 20:20:35 2017
*filter
:INPUT ACCEPT [111042:871714493]
:FORWARD ACCEPT [9:500]
:OUTPUT ACCEPT [79360:937635748]
COMMIT
# Completed on Thu Feb 23 20:20:35 2017
"

# captive portal NAT rules.
#echo $ipt | iptables-restore

#cd /home/$(whoami)/sdn-authenticator-webserver/
#nohup java -cp uber-captive-portal-webserver-1.0-SNAPSHOT.jar Main config.yaml > /home/$(whoami)/portal_webserver.out 2>&1 &
#echo $! > /home/$(whoami)/portal_webserver_pid.txt
cd /root/
nohup /root/hostapd-d1xf/hostapd/hostapd -d /root/hostapd-d1xf/hostapd/wired.conf > hostapd.out 2>&1 &
echo $! > /root/hostapd_pid.txt
